- gpib_address: ''
  ip_address: ''
  mode: '0'
  name: DUT
  port: ''
- gpib_address: ''
  ip_address: ''
  mode: '0'
  name: INSTR02
  port: ''
- gpib_address: ''
  ip_address: ''
  mode: '0'
  name: INSTR03
  port: ''
- gpib_address: ''
  ip_address: ''
  mode: '0'
  name: INSTR04
  port: ''
