f5560A:
  ip_address: 129.196.136.130
  port: '3490'
  gpib_address: ''
  mode: SOCKET
k34461A:
  ip_address: 10.205.92.67
  port: '3490'
  gpib_address: ''
  mode: SOCKET
f8846A:
  ip_address: 10.205.92.248
  port: '3490'
  gpib_address: ''
  mode: SOCKET
f5520A:
  ip_address: ''
  port: ''
  gpib_address: '6'
  mode: GPIB
