f5560A:
  ip_address: 129.196.136.130
  port: '3490'
  gpib_address: ''
  mode: NIGHTHAWK
k34461A:
  ip_address: 10.205.92.155
  port: '3490'
  gpib_address: ''
  mode: INSTR
f8846A:
  ip_address: 10.205.92.113
  port: '3490'
  gpib_address: ''
  mode: SOCKET
f5790A:
  ip_address: ''
  port: ''
  gpib_address: '6'
  mode: GPIB
